In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Numpy Intro

In [2]:
# Numpy Array
np_array = np.array([2,3,4,6,12,23,67])

In [3]:
type(np_array)

numpy.ndarray

In [4]:
np_array.shape

(7,)

In [5]:
np.ndim(np_array)

1

In [6]:
arr_1 = np.arange(6)

In [7]:
arr_1

array([0, 1, 2, 3, 4, 5])

In [8]:
arr_2 = np.arange(10,24)
print(arr_2)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [9]:
arr_3 = np.arange(10,24,2)
print(arr_3)

[10 12 14 16 18 20 22]


In [13]:
arr_4 = np.random.random(10) * 10
print(arr_4)

[ 8.08705574  4.13510835  2.05110846  8.55100081  3.33873274  3.69465062
  8.04753053  1.4399165   0.07241587  0.13982401]


In [14]:
arr_5 = np.random.randint(0,20)
print(arr_5)

8


In [15]:
arr_5 = np.random.randint(0,20,10)
print(arr_5)

[ 0  5 11 19 10 18 12 19 18  1]


In [17]:
z = np.zeros((6,6))
print(z)

[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]


In [18]:
o = np.ones((4,5))
print(o)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [19]:
o.shape

(4, 5)

In [20]:
np.ndim(o)

2

In [23]:
arr_6 = np.linspace(10,20, 5, dtype='int')
print(arr_6)

[10 12 15 17 20]


# N-Dimensional Array

In [24]:
nd_1 = np.ndarray((4,4))
print(nd_1)

[[  1.50451571e-311   1.50457428e-311   1.50451564e-311   1.50457550e-311]
 [  1.50451690e-311   1.50457428e-311   1.50451564e-311   1.50456600e-311]
 [  1.50451690e-311   1.50457428e-311   1.50451564e-311   1.50457428e-311]
 [  1.50451690e-311   1.50454396e-311   1.50451564e-311   1.50454396e-311]]


In [26]:
nd_2 = np.ndarray(5)
print(nd_2)

[ 10.   12.5  15.   17.5  20. ]


In [27]:
nd_2 = np.ndarray(10)
print(nd_2)

[ 8.08705574  4.13510835  2.05110846  8.55100081  3.33873274  3.69465062
  8.04753053  1.4399165   0.07241587  0.13982401]


In [33]:
nd_3 = np.ndarray([5,5,1])
print(nd_3)

[[[  7.74860419e-304]
  [  7.74860419e-304]
  [  7.74860419e-304]
  [  7.74860419e-304]
  [  7.74860419e-304]]

 [[  7.74860419e-304]
  [  7.74860419e-304]
  [  7.74860419e-304]
  [  7.74860419e-304]
  [  7.74860419e-304]]

 [[  7.74860419e-304]
  [  7.74860419e-304]
  [  7.74860419e-304]
  [  7.74860419e-304]
  [  7.74860419e-304]]

 [[  7.74860419e-304]
  [  7.74860419e-304]
  [  7.74860419e-304]
  [  7.74860419e-304]
  [  7.74860419e-304]]

 [[  7.74860419e-304]
  [  7.74860419e-304]
  [  7.74860419e-304]
  [  7.74860419e-304]
  [  7.74860419e-304]]]


In [34]:
nd_3.shape

(5, 5, 1)

In [35]:
nd_3.ndim

3

In [36]:
x1 = np.array([
    [2,3,4],
    [5,6,7],
    [8,9,10]
])

In [37]:
x1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [38]:
x1[0]

array([2, 3, 4])

In [40]:
x1[0:2]

array([[2, 3, 4],
       [5, 6, 7]])

In [41]:
x1[:,0:2]

array([[2, 3],
       [5, 6],
       [8, 9]])