In [1]:
import tensorflow as tf
import numpy as np

In [2]:
sess = tf.InteractiveSession()

In [3]:
tensor_1 = np.random.uniform(1,12,(4,3))

In [4]:
x = tf.Variable(initial_value=tensor_1)

In [19]:
tensor_2 = tf.random_uniform((4,3),1,12, dtype=tf.float64)

In [20]:
y = tf.Variable(initial_value=tensor_2)

In [21]:
init = tf.global_variables_initializer()

In [22]:
init.run()

In [23]:
sess.run(x)

array([[  3.56409436,   9.41057983,   3.53891751],
       [ 10.78541208,   5.12451294,   7.2135353 ],
       [  9.29393911,   3.0281351 ,   2.34869636],
       [  4.41039833,   1.01402987,   5.08689341]])

In [24]:
sess.run(y)

array([[  3.52721599,   9.95765982,   3.10938824],
       [  4.79917913,  11.2102124 ,   3.79077281],
       [  5.4714876 ,   5.69470201,   5.75141288],
       [  4.21409921,  11.55307797,   9.01493916]])

In [25]:
z = x + y

In [26]:
sess.run(z)

array([[  7.09131035,  19.36823966,   6.64830575],
       [ 15.58459122,  16.33472535,  11.00430811],
       [ 14.76542671,   8.7228371 ,   8.10010925],
       [  8.62449754,  12.56710784,  14.10183257]])

In [27]:
ones = tf.ones((4,4))

In [28]:
zeros = tf.zeros((4,4))

In [29]:
sess.run(ones)

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]], dtype=float32)

In [30]:
sess.run(zeros)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]], dtype=float32)

In [31]:
z1 = tf.add(x,y)

In [32]:
sess.run(z1)

array([[  7.09131035,  19.36823966,   6.64830575],
       [ 15.58459122,  16.33472535,  11.00430811],
       [ 14.76542671,   8.7228371 ,   8.10010925],
       [  8.62449754,  12.56710784,  14.10183257]])

In [33]:
# Placeholder
p1 = tf.placeholder(tf.float32, shape=(None,4))