In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
sess = tf.InteractiveSession()

In [8]:
np.random.seed(101)
tf.set_random_seed(101)

In [14]:
a = np.random.uniform(0,100,(5,5))

In [15]:
a

array([[ 51.63986277,  57.06675869,   2.84742265,  17.15216562,
         68.52769817],
       [ 83.38968626,  30.69662197,  89.36130797,  72.15438618,
         18.99389542],
       [ 55.42275911,  35.2131954 ,  18.18924027,  78.56017619,
         96.54832224],
       [ 23.23536618,   8.35614337,  60.35484223,  72.89927573,
         27.62388285],
       [ 68.53063288,  51.78674742,   4.84845374,  13.78692376,
         18.69674261]])

In [16]:
b = np.random.uniform(0,100,(5,1))

In [17]:
b

array([[ 99.43179012],
       [ 52.06653967],
       [ 57.87895355],
       [ 73.48190583],
       [ 54.19617722]])

In [18]:
x = tf.placeholder(tf.float64)
y = tf.placeholder(tf.float64)

In [23]:
add = x + y
mul = x * y

In [25]:
with tf.Session() as session:
    add_opr = session.run(add, feed_dict={x : a, y : b})
    print(add_opr)
    print("--------------------------")
    mul_opr = session.run(mul, feed_dict={x : a, y : b})
    print(mul_opr)

[[ 151.07165289  156.4985488   102.27921276  116.58395574  167.95948829]
 [ 135.45622593   82.76316164  141.42784764  124.22092585   71.06043509]
 [ 113.30171266   93.09214895   76.06819381  136.43912973  154.42727579]
 [  96.71727201   81.83804919  133.83674806  146.38118156  101.10578868]
 [ 122.7268101   105.98292464   59.04463097   67.98310098   72.89291984]]
--------------------------
[[ 5134.64399656  5674.24997231   283.12433109  1705.4705322   6813.8317015 ]
 [ 4341.81240779  1598.26688535  4652.73408616  3756.82921013
    988.94640937]
 [ 3207.81130015  2038.10290097  1052.77419242  4546.98078818
   5588.11585809]
 [ 1707.3789896    614.02533992  4434.98883288  5356.77771395
   2029.85555814]
 [ 3714.09832466  2806.64374096   262.76765829   747.19856325
   1013.29197619]]


In [27]:
n_features = 10
hidden_layer_neurons = 3

In [59]:
x = tf.placeholder(tf.float32, shape=(None,n_features))

In [60]:
w = tf.Variable(tf.random_normal([n_features,hidden_layer_neurons]))

In [61]:
b = tf.Variable(tf.zeros([hidden_layer_neurons]))

In [62]:
xw = tf.matmul(x,w)

In [63]:
add = tf.add(xw, b)

In [64]:
sigmoid = tf.sigmoid(add)

In [73]:
init = tf.global_variables_initializer()

In [74]:
init.run()

In [76]:
out_layer = sess.run(sigmoid, feed_dict={x : np.random.random([1,n_features])})

In [77]:
print(out_layer)

[[ 0.16180953  0.42958668  0.98700511]]
